import {inspectRange,inspectBoolean} from './model.js';
const $=s=>document.querySelector(s), ns='http://www.w3.org/2000/svg';
const choice=$('#function'), buildButtons=[...document.querySelectorAll('[data-build]')];
let builds,native,optimization='O0',paused=false;
const preference=matchMedia('(prefers-reduced-motion: reduce)');
const notes={bounded_range:'The offset is checked before subtraction. Compare the graph at O0 and O2: the predicate survives a change of shape.',legacy_range:'Unsigned addition wraps at 2³². A comparison after that wrap can approve a range outside the buffer.',canonical_boolean:'Only byte values 0 and 1 are accepted. Every other encoded byte produces the explicit invalid result −1.',legacy_boolean:'The test is nonzero, so all 255 nonzero byte values collapse to the same result.'};
function motion(){const on=!paused&&!preference.matches&&!document.hidden;document.body.dataset.motion=on?'on':'off';$('#motion').textContent=preference.matches?'Motion / reduced':`Motion / ${on?'on':'off'}`;$('#motion').setAttribute('aria-pressed',String(on));$('#motion').disabled=preference.matches;}
function svg(tag,attrs,text){const e=document.createElementNS(ns,tag);for(const [k,v] of Object.entries(attrs||{}))e.setAttribute(k,String(v));if(text!==undefined)e.textContent=text;return e;}
function graph(fn){
 const flow=$('#flow');flow.replaceChildren(svg('title',{id:'flow-title'},`${fn.name}: recovered control-flow graph`),svg('desc',{id:'flow-desc'},`${fn.blocks.length} basic blocks. The instruction listing provides a text alternative.`));
 const defs=svg('defs'),marker=svg('marker',{id:'arrow',viewBox:'0 0 10 10',refX:9,refY:5,markerWidth:5,markerHeight:5,orient:'auto-start-reverse'});marker.append(svg('path',{d:'M0 0L10 5L0 10Z',fill:'#d87866'}));defs.append(marker);flow.append(defs);
 const blocks=fn.blocks,depth=new Map(),order=new Map(blocks.map((b,i)=>[b.start,i]));
 // These controlled fixtures have forward edges; use longest-path layers so merge blocks follow both predecessors.
 blocks.forEach((b,i)=>{if(!depth.has(b.start))depth.set(b.start,0);for(const edge of b.edges)if(order.has(edge.to)&&order.get(edge.to)>i)depth.set(edge.to,Math.max(depth.get(edge.to)||0,depth.get(b.start)+1));});
 const levels=new Map();for(const block of blocks){const d=depth.get(block.start)??0;if(!levels.has(d))levels.set(d,[]);levels.get(d).push(block);}
 const positions=new Map(),width=660,height=Math.max(220,(Math.max(0,...levels.keys())+1)*142+32);flow.setAttribute('viewBox',`0 0 ${width} ${height}`);
 for(const [level,list] of levels)list.forEach((b,i)=>positions.set(b.start,{x:width/(list.length+1)*(i+1),y:35+level*142}));
 for(const b of blocks)for(const edge of b.edges){if(!positions.has(edge.to))continue;const a=positions.get(b.start),z=positions.get(edge.to);const skip=z.y-a.y>160&&Math.abs(z.x-a.x)<20;const edgePath=skip?`M${a.x+91} ${a.y+35} C${a.x+220} ${a.y+35},${z.x+220} ${z.y+35},${z.x+91} ${z.y+35}`:`M${a.x} ${a.y+69} C${a.x} ${a.y+105},${z.x} ${z.y-25},${z.x} ${z.y}`;flow.append(svg('path',{d:edgePath,class:'flow-edge','marker-end':'url(#arrow)'}));flow.append(svg('text',{x:skip?a.x+155:(a.x+z.x)/2+7,y:(a.y+z.y)/2+33,class:'edge-label'},edge.kind));}
 for(const b of blocks){const p=positions.get(b.start),group=svg('g',{class:`graph-node${b.start===fn.entry?' is-entry':''}`});group.append(svg('rect',{x:p.x-91,y:p.y,width:182,height:70,rx:1}),svg('text',{x:p.x-75,y:p.y+24},b.start),svg('text',{x:p.x-75,y:p.y+47,class:'node-count'},`${b.instructions.length} instructions · ${b.instructions.at(-1)?.text.split(' ')[0]||'END'}`));flow.append(group);}
 $('#graph-count').textContent=`${blocks.length} BLOCK${blocks.length===1?'':'S'}`;
}
function inspect(){
 if(!builds)return;const isBoolean=choice.value.includes('boolean');$('#range-inputs').hidden=isBoolean;$('#boolean-inputs').hidden=!isBoolean;$('#challenge-explanation').textContent=isBoolean?'A nonzero byte and a canonical Boolean encoding answer different questions. The corrected decoder returns −1 for invalid encodings.':'Unsigned addition can wrap before the comparison. The corrected predicate bounds the offset before subtraction.';
 try{const result=isBoolean?inspectBoolean($('#byte').value):inspectRange($('#total').value,$('#offset').value,$('#count').value);$('#input-error').textContent='';$('#legacy-result').textContent=isBoolean?String(result.legacy):(result.legacy?'ACCEPT':'REJECT');$('#corrected-result').textContent=result.corrected===-1?'INVALID':isBoolean?String(result.corrected):(result.corrected?'ACCEPT':'REJECT');$('#arithmetic').textContent=isBoolean?`Encoded byte ${$('#byte').value} → nonzero predicate ${result.legacy}; canonical result ${result.corrected}.`:`Exact sum: ${result.sum} · uint32 sum: ${result.wrapped}`;}catch(error){$('#input-error').textContent=error.message;$('#legacy-result').textContent='—';$('#corrected-result').textContent='—';$('#arithmetic').textContent='Enter a valid unsigned value to evaluate.';}
}
function render(){const fn=builds[optimization].functions.find(f=>f.name===choice.value);if(!fn)throw new Error('Missing function in recorded analysis');$('#function-note').textContent=notes[fn.name];$('#decompiled').textContent=fn.decompiled_c.trim();$('#entry').textContent=fn.entry;$('#instruction-count').textContent=`${fn.instruction_count} INSTRUCTIONS`;$('#assembly').textContent=fn.blocks.flatMap(b=>b.instructions.map(i=>`${i.address}  ${i.bytes.padEnd(26)}  ${i.text}`)).join('\n');buildButtons.forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.build===optimization)));graph(fn);inspect();}
async function json(path){const r=await fetch(path);if(!r.ok)throw new Error(`Report unavailable (${r.status})`);return r.json();}
async function start(){
 try{const [o0,o2,tests,provenance]=await Promise.all(['analysis-O0.json','analysis-O2.json','native-tests.json','provenance.json'].map(json));builds={O0:o0,O2:o2};native=tests;
 for(const key of ['O0','O2']){const n=native.builds.find(x=>x.optimization===key);if(builds[key].functions?.length!==4||builds[key].binary_sha256!==n?.sha256)throw new Error('Analysis and native-test artifact hashes disagree');}
 $('#ghidra-version').textContent=o0.ghidra_version;$('#false-accepts').textContent=tests.builds[0].legacy_range_false_accepts.toLocaleString();$('#corrected-errors').textContent=tests.builds.reduce((n,b)=>n+b.canonical_boolean_errors+b.bounded_range_errors,0);$('#provenance').textContent=JSON.stringify(provenance,null,2);
 for(const b of tests.builds){const tr=document.createElement('tr');for(const value of [b.optimization,b.boolean_inputs,b.range_inputs,b.legacy_range_false_accepts,b.canonical_boolean_errors+b.bounded_range_errors]){const td=document.createElement('td');td.textContent=typeof value==='number'?value.toLocaleString():value;tr.append(td);}$('#test-rows').append(tr);}
 choice.disabled=false;buildButtons.forEach(b=>b.disabled=false);$('#report-status').textContent='RECORDED ANALYSIS / ARTIFACT HASHES MATCH';render();motion();
 }catch(error){$('#report-status').textContent='ANALYSIS UNAVAILABLE';$('#decompiled').textContent=error.message;$('#function-note').textContent='The source and documentation links remain available. Recorded results could not be verified.';builds=null;}
}
choice.addEventListener('change',render);buildButtons.forEach(b=>b.addEventListener('click',()=>{optimization=b.dataset.build;render();}));document.querySelectorAll('.inputs input').forEach(i=>i.addEventListener('input',inspect));$('#reset-inputs').addEventListener('click',()=>{$('#total').value='16';$('#offset').value='4294967295';$('#count').value='2';$('#byte').value='2';inspect();});$('#motion').addEventListener('click',()=>{paused=!paused;motion();});preference.addEventListener('change',motion);document.addEventListener('visibilitychange',motion);start();
